#!/usr/bin / env node

/**
 * Interactive setup wizard.
 * Guides a user through first-time configuration.
 *
 * Usage: node scripts/setup-wizard.mjs
 */

import { createInterface } from 'readline'
import { existsSync, readFileSync, writeFileSync, copyFileSync } from 'fs'
import { join, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = join(__dirname, '..')

const rl = createInterface({
  input: process.stdin,
  output: process.stdout,
})

function ask(question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()))
  })
}

function hr() {
  console.log('─'.repeat(60))
}

async function main() {
  console.log('')
  console.log('╔══════════════════════════════════════════════════════════╗')
  console.log('║         Cursor → Jira Integration Setup Wizard         ║')
  console.log('╚══════════════════════════════════════════════════════════╝')
  console.log('')

  // ── Check Node version ──────────────────────────────
  const [major] = process.versions.node.split('.').map(Number)
  if (major < 18) {
    console.error(
      `❌ Node.js ${process.versions.node} is too old.Need >= 18.3.0`,
    )
    console.error('   Download: https://nodejs.org')
    process.exit(1)
  }
  console.log(`✅ Node.js ${process.versions.node} `)

  // ── Check npm install ───────────────────────────────
  const hasNodeModules = existsSync(join(ROOT, 'node_modules'))
  if (!hasNodeModules) {
    console.log('')
    console.log('📦 Dependencies not installed. Running npm install...')
    const { execSync } = await import('child_process')
    try {
      execSync('npm install', { cwd: ROOT, stdio: 'inherit' })
      console.log('✅ Dependencies installed')
    } catch {
      console.error('❌ npm install failed. Try running it manually:')
      console.error('   cd', ROOT)
      console.error('   npm install')
      process.exit(1)
    }
  } else {
    console.log('✅ Dependencies installed')
  }

  // ── Gather information ──────────────────────────────
  hr()
  console.log('')
  console.log("Let's configure your Jira connection.")
  console.log("I'll ask a few questions. Hit Enter to accept [defaults].")
  console.log('')

  // Domain
  console.log(
    '1. Your Jira URL looks like: https://SOMETHING.atlassian.net',
  )
  console.log('   What is the SOMETHING part?')
  console.log('')
  const domain = await ask('   Jira domain: ')
  if (!domain) {
    console.error('   ❌ Domain is required.')
    process.exit(1)
  }

  // Email
  console.log('')
  console.log('2. What email do you log into Jira with?')
  console.log('')
  const email = await ask('   Email: ')
  if (!email || !email.includes('@')) {
    console.error('   ❌ A valid email is required.')
    process.exit(1)
  }

  // API Token
  console.log('')
  hr()
  console.log('')
  console.log('3. Now we need an API token. Follow these steps:')
  console.log('')
  console.log(
    '   a. Open this URL in your browser:',
  )
  console.log(
    '      https://id.atlassian.com/manage-profile/security/api-tokens',
  )
  console.log('')
  console.log('   b. Click "Create API token"')
  console.log('   c. Label it "Cursor Integration"')
  console.log('   d. Click Create, then Copy the token')
  console.log('')
  console.log(
    '   ⚠️  The token is only shown once. Copy it before closing.',
  )
  console.log('')
  const token = await ask('   Paste your API token here: ')
  if (!token || token.length < 10) {
    console.error(
      '   ❌ That doesn\'t look like a valid token. They\'re usually 24+ characters.',
    )
    process.exit(1)
  }

  // Project key
  console.log('')
  console.log(
    '4. Your Jira issues have a prefix like DPH-123 or ENG-456.',
  )
  console.log('   What letters do YOUR issues start with?')
  console.log('')
  const project = (
    await ask('   Project key [DPH]: ')
  ).toUpperCase() || 'DPH'

  // Confluence
  console.log('')
  console.log('5. Do you use Confluence? (y/n)')
  const useConfluence = (await ask('   [y]: ')).toLowerCase() !== 'n'

  let confluenceSpace = ''
  if (useConfluence) {
    console.log('')
    console.log(
      '   What is your main Confluence space key?',
    )
    console.log(
      '   (Found in URLs like /spaces/ENG/...)',
    )
    confluenceSpace = (
      await ask(`   Space key[${project}]: `)
    ).toUpperCase() || project
  }

  // ── Write .env ──────────────────────────────────────
  hr()
  console.log('')
  console.log('Creating configuration files...')
  console.log('')

  const envContent = [
    '# Generated by setup wizard',
    `# ${new Date().toISOString()} `,
    '',
    `JIRA_EMAIL = ${email} `,
    `JIRA_API_TOKEN = ${token} `,
    '',
  ].join('\n')

  const envPath = join(ROOT, '.env')
  if (existsSync(envPath)) {
    const overwrite = await ask(
      '   .env already exists. Overwrite? (y/n) [n]: ',
    )
    if (overwrite.toLowerCase() !== 'y') {
      console.log('   Keeping existing .env')
    } else {
      writeFileSync(envPath, envContent)
      console.log('   ✅ .env updated')
    }
  } else {
    writeFileSync(envPath, envContent)
    console.log('   ✅ .env created')
  }

  // ── Write config.yaml ──────────────────────────────
  const configContent = `# Generated by setup wizard — ${new Date().toISOString()}
# Edit this file to add projects, spaces, or additional profiles.

  profiles:
  default: main

main:
domain: ${domain}
browse_domain: ${domain}

auth:
email_env: JIRA_EMAIL
token_env: JIRA_API_TOKEN

jira:
default_project: ${project}
projects:
- key: ${project}

sprint_jql: > -
  sprint in openSprints() AND project = \${ project }
        ORDER BY priority ASC, status ASC, key ASC
my_jql: > -
  assignee = currentUser() AND statusCategory != Done
        ORDER BY priority ASC, updated DESC

status_order:
- In Progress
  - Ready for Review
    - To Do
  - Done

    confluence:
  default_space: ${confluenceSpace || project}
spaces:
- key: ${confluenceSpace || project}
`

  const configPath = join(ROOT, 'config.yaml')
  if (existsSync(configPath)) {
    const overwrite = await ask(
      '   config.yaml already exists. Overwrite? (y/n) [n]: ',
    )
    if (overwrite.toLowerCase() !== 'y') {
      console.log('   Keeping existing config.yaml')
    } else {
      writeFileSync(configPath, configContent)
      console.log('   ✅ config.yaml updated')
    }
  } else {
    writeFileSync(configPath, configContent)
    console.log('   ✅ config.yaml created')
  }

  // ── Verify connection ──────────────────────────────
  hr()
  console.log('')
  console.log('Testing connection to Jira...')
  console.log('')

  try {
    // Dynamically import after npm install and .env creation
    const dotenv = await import('dotenv')
    dotenv.config({ path: envPath, override: true })

    const { loadConfig } = await import('../lib/config.mjs')
    const { createClient } = await import('../lib/client.mjs')

    const config = loadConfig()
    const client = createClient(config)
    const user = await client.requestJson('/rest/api/3/myself', {}, 'setup verify')

    console.log(`   ✅ Connected as: ${user.displayName} (${user.emailAddress})`)
    console.log('')
  } catch (err) {
    console.log(`   ❌ Connection failed: ${err.message} `)
    console.log('')
    console.log('   This usually means:')
    console.log('   • The API token was copied incorrectly')
    console.log('   • The email doesn\'t match your Atlassian account')
    console.log(`   • The domain "${domain}" is wrong`)
    console.log('')
    console.log('   You can edit .env and config.yaml manually and try:')
    console.log('   node bin/jira-cli.mjs me')
    console.log('')
    rl.close()
    process.exit(1)
  }

  // ── Done ────────────────────────────────────────────
  hr()
  console.log('')
  console.log('🎉 Setup complete! Try these commands:')
  console.log('')
  console.log('   node bin/jira-cli.mjs my            — Your open issues')
  console.log('   node bin/jira-cli.mjs sprint         — Current sprint board')
  console.log('   node bin/jira-cli.mjs get ' + project + '-1     — Get an issue')
  console.log('   node bin/jira-cli.mjs --help         — All commands')
  if (useConfluence) {
    console.log('   node bin/jira-cli.mjs spaces         — Confluence spaces')
    console.log('   node bin/jira-cli.mjs conf-search "query"  — Search docs')
  }
  console.log('')
  console.log('💡 Tip: Ask Cursor AI "set up a shell alias for jira"')
  console.log('   to create a shortcut so you can just type: jira my')
  console.log('')

  rl.close()
}

main().catch((err) => {
  console.error('Setup failed:', err.message)
  rl.close()
  process.exit(1)
})
